import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Navbar } from "~/components/Navbar";
import { Footer } from "~/components/Footer";
import { useState } from "react";
import { StudentInformation } from "~/components/StudentInformation";
import { MealSelection } from "~/components/MealSelection";
import { OrderConfirmation } from "~/components/OrderConfirmation";
import { Payment } from "~/components/Payment";
import { useMyStore, useThemeStore } from "../state/index";

export const steps = [
  "Student Information",
  "Meal Selection",
  "Order Confirmation",
  "Payment",
  "Done",
];

const Home: NextPage = () => {
  // const [step, setStep] = useState(0);
  const { step, increment, decrement } = useMyStore((state) => ({
    step: state.step,
    increment: state.increment,
    decrement: state.decrement,
  }));

  const { theme } = useThemeStore();

  const PageSwitcher: React.FC<{ stepValue: number }> = ({ stepValue }) => {
    return (
      <>
        {stepValue === 0 ? (
          <StudentInformation />
        ) : stepValue === 1 ? (
          <MealSelection />
        ) : stepValue === 2 ? (
          <OrderConfirmation />
        ) : stepValue === 3 ? (
          <Payment />
        ) : (
          <h2>Nothing</h2>
        )}
      </>
    );
  };
  return (
    <>
      <Head>
        <title>Freshii Ottawa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex min-h-screen flex-col items-center justify-center "
        data-theme={theme}
      >
        <Navbar />
        {/* Stepper */}
        <div className="my-2 mx-auto">
          <ul className="steps">
            {steps.map((each, idx) => (
              <li
                key={idx}
                className={`${step === idx ? "step-accent" : ""} step`}
              >
                {each}
              </li>
            ))}
          </ul>
        </div>
        <main className=" flex-grow">
          <PageSwitcher stepValue={step} />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
